Postgresql
ncleyetmarrel/test_ecg_qc pull request #2
Opened 2021-06-21 08:42 UTC by ncleyetmarrel

2021-07-01 15:40 UTC, robinchampseix requested changes

2021-07-01 15:40 UTC, robinchampseix commented on .github/workflows/main.yml
>      runs-on: ubuntu-latest
Ne pas utiliser "latest" et **fixer la version**. Avec les évolutions, ça pourrait casser des choses... :)

2021-07-01 15:40 UTC, robinchampseix commented on DockerfileCustomAirflow
> +FROM python:3.7-slim-buster
Pourquoi avoir copié collé cette Dockerfile ici ? Quid de l'usage de l'image Airflow de Puckel ? :-)

2021-07-01 15:40 UTC, robinchampseix commented on README.md
> +    $ sudo chmod -R 777 output/ data/ logs/ scripts/
777.... Aïe mes yeux ^^

Ya pas une autre façon de faire ? créer un user, qui lui a les droits ? T'as pu essayer d'utiliser l'image AIrflow de puckel ? :)

2021-07-01 15:40 UTC, robinchampseix commented on conf/provisioning/datasources/datasources.yml
> +apiVersion: 1
Pourquoi est ce que le fichier **datasources.yml** est là ? On le génère avec les commandes du README.md, non?

2021-07-01 15:40 UTC, robinchampseix commented on env.sh
> +# IDs
Tu peux me rappeler pourquoi tu génères l'UID & le GUID ? :)

2021-07-01 15:40 UTC, robinchampseix commented on logs/.gitignore
> +# Ignore everything in this directory
Pourquoi t'as un dossier logs ?

2021-07-01 15:40 UTC, robinchampseix commented on output/.gitignore
> +# Ignore everything in this directory
Pourquoi t'as un dosier output ?

2021-07-01 15:40 UTC, robinchampseix commented on test/test_compute_metrics.py
> +    assert (get_scores(420, 935, 923) == [31.0, 31.27, 31.13])
L5: Je crois que les parenthèses sont inutiles...

2021-07-01 15:40 UTC, robinchampseix commented on scripts/entrypoint.sh
> +#!/usr/bin/env bash
Il est utilisé ou cet **entrypoint** ? Il sertà quoi déjà ? :)

2021-07-01 15:40 UTC, robinchampseix commented on scripts/create_multiple_databases.sh
> +#!/bin/bash
Pourquoi créer une base en shell et pas avec les API Python ? Et il est utilisé ou ce script ? Il sert à quoi ? Je vois pas d'infos dessus ... :)

2021-07-01 15:40 UTC, robinchampseix commented on dags/main_dag.py
> +from datetime import datetime
convention **PEP8**: 
Import dep python 
saut de ligne
import package installés via pip
saut de ligne
import package custom

J'ai un linter intégré à mon oeil gauche... ;-)

2021-07-01 15:40 UTC, robinchampseix commented on dags/main_dag.py
> +model_ECG_QC = ['rfc', 'xgb', 'model']
Convention: Toutes les valeurs "hard codées" en MAJUSCULE
L16, 17, 18 etc ... :-)

2021-07-01 15:40 UTC, robinchampseix commented on dags/main_dag.py
> +    concurrency=12
12 à extraire dans une variable (d'environnement ?) en haut ;)

2021-07-01 15:40 UTC, robinchampseix commented on dags/main_dag.py
> +    concurrency=12
Je vois du code dupliqué pour les 2 dags... Variables en haut de fichier ?

-  start_date=datetime(2021, 4, 22),
-  schedule_interval=None,
-  concurrency=12

2021-07-01 15:40 UTC, robinchampseix commented on dags/main_dag.py
> +from datetime import datetime
Tu penses quoi de trouver un nom plus parlant que "main_dag" pour le fichier ?

2021-07-01 15:40 UTC, robinchampseix commented on dags/tasks/apply_ecg_qc.py
> +from psycopg2.extensions import cursor
saut de ligne ;-) #PEP8

2021-07-01 15:40 UTC, robinchampseix commented on dags/tasks/apply_ecg_qc.py
> +# lib_path = os.path.dirname(ecg_qc.__file__)
À supprimer ?

2021-07-01 15:40 UTC, robinchampseix commented on dags/tasks/apply_ecg_qc.py
> +def filter_list(liste: List, df: pd.DataFrame) -> List:
Quelques remarques sur cette fonction:

- Le nom filter_list me parait trop générique...
- le nom de variable "liste" idem
- Tu pourrais faire créer une fonction avec un nom porteur de sens pour les lignes 41 à 44 et appeler cette fonction dans une "list comprehension" pour faire pythonesque
- Tu pourrais extraire dans une variable "len(df[(timestamp >= df['start']) & (df['end'] >= timestamp)]) == 0" pour donner un nom compréhensible

2021-07-01 15:40 UTC, robinchampseix commented on dags/tasks/apply_ecg_qc.py
> +        cursor.execute("CREATE TABLE noisy_info \
Ça serait + clean d'extraire ces requpetes en mode "magic string" dans des fichiers **".sql"** et les importer dans ton code...

2021-07-01 15:40 UTC, robinchampseix commented on dags/tools/grafana_client.py
> +# import datetime
N'aie pas peur de supprimer tous les commentaires et ce qui n'est pas nécessaire ;)

2021-07-01 15:40 UTC, robinchampseix commented on dags/tasks/write_annot_to_db.py
> +def get_connection_to_db(host: str = "influxdb", port: int = 8086,
Attention à ne pas mettre certains paramètres en dur car on pourrait vouloir les charger en var d'env ou en dur pour les injecter à chaque appel de cette fonctions
ex:      client = get_connection_to_db()
Tu passes aucun params donc tu supposes que ya des vars par défaut qui marcheraint tout le temps... Ce qui peut ne pas etre le cas

Je sais pas si je suis clair ?

2021-07-01 15:40 UTC, robinchampseix commented on dags/tasks/write_annot_to_db.py
> +    json_file = 'output/annotations/mit_bih_noise_stress.json'
Oupsi, hard coded variable... En haut du magic, en MAJ

2021-07-01 15:40 UTC, robinchampseix commented on dags/tasks/delete_model.py
> +    client = GrafanaClient("http://grafana:3000", key)
attention aux magic string dans le code ...

2021-07-05 08:38 UTC, ncleyetmarrel commented on DockerfileCustomAirflow
> +FROM python:3.7-slim-buster
En fait c'est presque le même dockerfile que puckel/airflow, il fallait que je lui apporte deux trois modifs pour avoir une image qui marchait comme je voulais

2021-07-05 08:40 UTC, ncleyetmarrel commented on README.md
> +    $ sudo chmod -R 777 output/ data/ logs/ scripts/
Normalement avec les modifs apportées au dockerfile il ne devrait plus y avoir de soucis, donc il faut que j'enlève cette ligne qui ne sert en théorie plus à rien (j'espère...)

2021-07-05 08:47 UTC, ncleyetmarrel commented on conf/provisioning/datasources/datasources.yml
> +apiVersion: 1
Effectivement j'ai oublié de le mettre dans le gitignore

2021-07-05 08:54 UTC, ncleyetmarrel commented on env.sh
> +# IDs
En fait lors de l'exécution de dags le container airflow va créer des fichiers dans output (des json/csv), et ce folder est un bind mount donc les fichiers sont accessibles en local (on veut les garder même si le container est down). Le problème c'est que le propriétaire de ces fichiers est airflow, donc du point de vue local l'utilisateur est pas sûr d'y avoir accès (typiquement le propriétaire devenait aura-admin et pas aura-nathan sur les serveurs de la teppe). D'où la nécessité que airflow ait le même UID/GID que l'utilisateur, pour pas avoir de problème de permission.

2021-07-05 08:56 UTC, ncleyetmarrel commented on logs/.gitignore
> +# Ignore everything in this directory
Je crois que le container airflow en a besoin, je t'avoue que je sais plus trop

2021-07-05 08:56 UTC, ncleyetmarrel commented on output/.gitignore
> +# Ignore everything in this directory
Pour stocker les fichiers csv/json issus des différentes tâches

2021-07-05 08:59 UTC, ncleyetmarrel commented on scripts/entrypoint.sh
> +#!/usr/bin/env bash
Il est utilisé par le conteneur airflow pour bien s'initialiser lors de son up

2021-07-05 09:02 UTC, ncleyetmarrel commented on scripts/create_multiple_databases.sh
> +#!/bin/bash
Je trouvais ça plus simple de créer les bonnes bases dès l'initialisation du conteneur (en passant par le docker compose). Ce script est appelé comme entrypoint, il sert à créer les différentes bases dans postgres pour les différents services (une pour airflow, une pour grafana)

2021-07-22 13:16 UTC, merged